# Generated by Django 4.2.11 on 2024-05-06 12:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('membership_number', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('dob', models.DateField(blank=True, default='1987-12-12', null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='NA', max_length=6)),
                ('dependent', models.CharField(choices=[('NOT DEPENDENT', 'not_dependent'), ('DEPENDENT', 'dependent')], default='NOT DEPENDENT', max_length=20)),
                ('relationship', models.CharField(choices=[('Child', 'Child'), ('Member', 'Member'), ('Spouse', 'Spouse'), ('Parent', 'Parent')], default='Member', max_length=10)),
                ('passport_photo', models.ImageField(blank=True, default='default_passport.jpg', null=True, upload_to='passports/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=20)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('next_of_kin_contact', models.CharField(max_length=20)),
                ('penalized', models.CharField(choices=[('NOT PENALIZED', 'not_penalized'), ('PENALIZED', 'penalized')], default='NOT PENALIZED', max_length=20)),
                ('total_penalties', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('number_of_dependents', models.PositiveIntegerField(default=0)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('submitter', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='proposed', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('date_of_death', models.DateField(blank=True, help_text='Enter date in YYYY-MM-DD format (e.g., 2024-03-27)', null=True)),
                ('mpesa_number', models.CharField(blank=True, default='0701411355', max_length=20)),
                ('contribution_window_start', models.DateField()),
                ('contribution_window_end', models.DateField()),
                ('case_number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('set_contribution_amount', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('run_penalties', models.CharField(choices=[('Run Penalties', 'run_penalties'), ('Penalties Not Run', 'penalties_not_run')], default='penalties_not_run', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Deceased')], default='ACTIVE', max_length=20)),
                ('cashed_out', models.CharField(choices=[('Cashed Out', 'cashed_out'), ('Not Cashed Out', 'not_cashed_out')], default='not_cashed_out', max_length=20)),
                ('deceased_name', models.ForeignKey(limit_choices_to={'status': 'ACTIVE'}, on_delete=django.db.models.deletion.CASCADE, related_name='deceased_cases', to='people.member')),
                ('membership_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_cases', to='people.member')),
            ],
        ),
    ]
